{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "simple.serviceAccountName" . }}
  labels:
{{ include "simple.labels" . | indent 4 }}
{{- end -}}
